[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base = "dark"
backgroundColor = "#080b10"
secondaryBackgroundColor = "#0e1117"
textColor = "#e0e0e0"
font = "sans serif"

[browser]
gatherUsageStats = false
